import { Resend } from 'resend'
import { NextRequest, NextResponse } from 'next/server'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const {
      firstName,
      lastName,
      email,
      phone,
      transactionType,
      neighbourhood,
      timeline,
      priceRange,
    } = body

    // Validation
    if (!firstName || !lastName || !email || !phone || !neighbourhood) {
      return NextResponse.json(
        { error: 'Required fields missing' },
        { status: 400 }
      )
    }

    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email address' },
        { status: 400 }
      )
    }

    // Format the lead email body
    const leadEmailHtml = `
      <div style="font-family: Inter, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px; background: #FAF8F5;">
        <div style="background: #1B2B4B; padding: 24px; border-radius: 4px; margin-bottom: 24px;">
          <h1 style="color: #C9963E; font-family: Georgia, serif; margin: 0; font-size: 24px;">
            New Realtor Match Request
          </h1>
          <p style="color: rgba(255,255,255,0.7); margin: 8px 0 0; font-size: 14px;">
            Calgary Realtor Finder — ${new Date().toLocaleDateString('en-CA', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>

        <div style="background: white; border: 1px solid rgba(45,45,45,0.1); border-radius: 4px; padding: 24px; margin-bottom: 16px;">
          <h2 style="color: #1B2B4B; font-family: Georgia, serif; font-size: 18px; margin: 0 0 16px;">
            Lead Details
          </h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #f0f0f0;">
              <td style="padding: 10px 0; color: #999; font-size: 13px; width: 40%;">Name</td>
              <td style="padding: 10px 0; color: #2D2D2D; font-size: 14px; font-weight: 600;">${firstName} ${lastName}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f0f0f0;">
              <td style="padding: 10px 0; color: #999; font-size: 13px;">Email</td>
              <td style="padding: 10px 0; color: #2D2D2D; font-size: 14px;"><a href="mailto:${email}" style="color: #C9963E;">${email}</a></td>
            </tr>
            <tr style="border-bottom: 1px solid #f0f0f0;">
              <td style="padding: 10px 0; color: #999; font-size: 13px;">Phone</td>
              <td style="padding: 10px 0; color: #2D2D2D; font-size: 14px;"><a href="tel:${phone}" style="color: #C9963E;">${phone}</a></td>
            </tr>
            <tr style="border-bottom: 1px solid #f0f0f0;">
              <td style="padding: 10px 0; color: #999; font-size: 13px;">Transaction Type</td>
              <td style="padding: 10px 0; color: #2D2D2D; font-size: 14px; font-weight: 600;">${transactionType || 'Not specified'}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f0f0f0;">
              <td style="padding: 10px 0; color: #999; font-size: 13px;">Neighbourhood</td>
              <td style="padding: 10px 0; color: #2D2D2D; font-size: 14px;">${neighbourhood}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f0f0f0;">
              <td style="padding: 10px 0; color: #999; font-size: 13px;">Timeline</td>
              <td style="padding: 10px 0; color: #2D2D2D; font-size: 14px;">${timeline || 'Not specified'}</td>
            </tr>
            <tr>
              <td style="padding: 10px 0; color: #999; font-size: 13px;">Price Range</td>
              <td style="padding: 10px 0; color: #2D2D2D; font-size: 14px;">${priceRange || 'Not specified'}</td>
            </tr>
          </table>
        </div>

        <div style="background: #C9963E; border-radius: 4px; padding: 16px; text-align: center;">
          <p style="color: white; margin: 0; font-size: 14px; font-weight: 600;">
            Respond within 2 hours for best conversion.
          </p>
          <p style="color: rgba(255,255,255,0.8); margin: 4px 0 0; font-size: 12px;">
            This lead was generated by Calgary Realtor Finder
          </p>
        </div>
      </div>
    `

    // Confirmation email to the lead
    const confirmationEmailHtml = `
      <div style="font-family: Inter, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px; background: #FAF8F5;">
        <div style="background: #1B2B4B; padding: 24px; border-radius: 4px; margin-bottom: 24px;">
          <h1 style="color: #C9963E; font-family: Georgia, serif; margin: 0; font-size: 24px;">
            Calgary Realtor Finder
          </h1>
          <p style="color: rgba(255,255,255,0.7); margin: 8px 0 0; font-size: 14px;">
            Alberta's local realtor resource
          </p>
        </div>

        <div style="background: white; border: 1px solid rgba(45,45,45,0.1); border-radius: 4px; padding: 32px;">
          <h2 style="color: #1B2B4B; font-family: Georgia, serif; font-size: 22px; margin: 0 0 16px;">
            Hi ${firstName}, we've got your request.
          </h2>
          <p style="color: #2D2D2D; font-size: 15px; line-height: 1.6; margin: 0 0 16px;">
            Thank you for reaching out. We're matching you with a RECA-licensed Calgary REALTOR® who specializes in <strong>${neighbourhood}</strong>.
          </p>
          <p style="color: #2D2D2D; font-size: 15px; line-height: 1.6; margin: 0 0 16px;">
            You can expect to hear from your matched agent within a few hours. They'll reach out by email or phone — whichever you prefer.
          </p>
          <div style="background: #FAF8F5; border-left: 3px solid #C9963E; padding: 16px; margin: 24px 0; border-radius: 0 4px 4px 0;">
            <p style="color: #1B2B4B; font-weight: 600; margin: 0 0 8px; font-size: 14px;">Your match summary:</p>
            <p style="color: #666; font-size: 13px; margin: 4px 0;">📍 Area: ${neighbourhood}</p>
            <p style="color: #666; font-size: 13px; margin: 4px 0;">🏠 Looking to: ${transactionType || 'Buy or sell'}</p>
            <p style="color: #666; font-size: 13px; margin: 4px 0;">📅 Timeline: ${timeline || 'To be discussed'}</p>
            <p style="color: #666; font-size: 13px; margin: 4px 0;">💰 Budget: ${priceRange || 'To be discussed'}</p>
          </div>
          <p style="color: #999; font-size: 13px; line-height: 1.6; margin: 24px 0 0;">
            This is a free service. We'll never share your information with more than one agent, and there is no obligation to proceed.
          </p>
        </div>

        <p style="color: #999; font-size: 12px; text-align: center; margin-top: 24px;">
          Calgary Realtor Finder · Calgary, Alberta · <a href="https://calgaryrealtorfinder.ca" style="color: #C9963E;">calgaryrealtorfinder.ca</a>
        </p>
      </div>
    `

    // Send lead notification to Nathan + BCC Gavin
    await resend.emails.send({
      from: 'Calgary Realtor Finder <hello@calgaryrealtorfinder.ca>',
      to: [process.env.NATHAN_EMAIL as string],
      bcc: [process.env.GAVIN_EMAIL as string],
      subject: `New Realtor Match — ${firstName} ${lastName} · ${neighbourhood} · ${transactionType || 'Buyer/Seller'}`,
      html: leadEmailHtml,
      replyTo: email,
    })

    // Send confirmation to the lead
    await resend.emails.send({
      from: 'Calgary Realtor Finder <hello@calgaryrealtorfinder.ca>',
      to: [email],
      subject: `We've matched you, ${firstName} — expect a call soon`,
      html: confirmationEmailHtml,
    })

    return NextResponse.json(
      { success: true, message: 'Match request received' },
      { status: 200 }
    )
  } catch (error) {
    console.error('Contact API error:', error)
    return NextResponse.json(
      { error: 'Failed to send. Please try again or call us directly.' },
      { status: 500 }
    )
  }
}

// Reject non-POST requests
export async function GET() {
  return NextResponse.json(
    { error: 'Method not allowed' },
    { status: 405 }
  )
}
